server:
  port: 8888

spring:
  application:
    name: config-server
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  cloud:
    config:
      server:
        git:
#          uri: file:///C:/git-local-repo
          uri: https://github.com/yeosu/spring-cloud-config.git
          default-label: master

management:
  endpoints:
    web:
      exposure:
        include: health